# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/common/channel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import wireless_modcod_pb2 as api_dot_common_dot_wireless__modcod__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pi/common/channel.proto\x12\x1c\x61\x61lyria.spacetime.api.common\x1a api/common/wireless_modcod.proto\"\x9b\x01\n\x0b\x42\x61ndProfile\x12(\n\x10\x63hannel_width_hz\x18\x02 \x01(\x04R\x0e\x63hannelWidthHz\x12R\n\nrate_table\x18\x03 \x01(\x0b\x32\x33.aalyria.spacetime.api.common.AdaptiveDataRateTableR\trateTableJ\x04\x08\x01\x10\x02J\x08\x08\x04\x10\x80\x80\x80\x80\x02*\x85\x01\n\x16\x43hannelSelectionMethod\x12$\n CHANNEL_SELECTION_METHOD_UNKNOWN\x10\x00\x12 \n\x1c\x41UTONOMOUS_CHANNEL_SELECTION\x10\x01\x12#\n\x1f\x43HANNEL_SELECTION_BY_CONTROLLER\x10\x02\x42\x44\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.common.channel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common'
  _globals['_CHANNELSELECTIONMETHOD']._serialized_start=251
  _globals['_CHANNELSELECTIONMETHOD']._serialized_end=384
  _globals['_BANDPROFILE']._serialized_start=93
  _globals['_BANDPROFILE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
