# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/common/platform.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import bent_pipe_pb2 as api_dot_common_dot_bent__pipe__pb2
from api.common import coordinates_pb2 as api_dot_common_dot_coordinates__pb2
from api.common import wireless_transceiver_pb2 as api_dot_common_dot_wireless__transceiver__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pi/common/platform.proto\x12\x1c\x61\x61lyria.spacetime.api.common\x1a\x1a\x61pi/common/bent_pipe.proto\x1a\x1c\x61pi/common/coordinates.proto\x1a%api/common/wireless_transceiver.proto\"\xb5\x05\n\x12PlatformDefinition\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n\x04type\x18\x0c \x01(\tR\x04type\x12\x46\n\x0b\x63oordinates\x18\x0e \x01(\x0b\x32$.aalyria.spacetime.api.common.MotionR\x0b\x63oordinates\x12\x62\n\rmotion_source\x18\x10 \x01(\x0e\x32=.aalyria.spacetime.api.common.PlatformDefinition.MotionSourceR\x0cmotionSource\x12\"\n\rmotion_ref_id\x18\x04 \x01(\tR\x0bmotionRefId\x12[\n\x11transceiver_model\x18\x0f \x03(\x0b\x32..aalyria.spacetime.api.common.TransceiverModelR\x10transceiverModel\x12[\n\x12\x62\x65nt_pipe_payloads\x18\x12 \x03(\x0b\x32-.aalyria.spacetime.api.common.BentPipePayloadR\x10\x62\x65ntPipePayloads\x12X\n\x10\x61\x64sb_transponder\x18\r \x01(\x0b\x32-.aalyria.spacetime.api.common.AdsbTransponderR\x0f\x61\x64sbTransponder\x12\x19\n\x08norad_id\x18\x11 \x01(\rR\x07noradId\"J\n\x0cMotionSource\x12\x12\n\x0eUNKNOWN_SOURCE\x10\x00\x12\x12\n\x0eSPACETRACK_ORG\x10\x01\x12\x12\n\x0e\x46LIGHTRADAR_24\x10\x02J\x04\x08\x01\x10\x02J\x04\x08\x05\x10\x08J\x04\x08\x08\x10\tJ\x04\x08\t\x10\nJ\x04\x08\n\x10\x0bJ\x04\x08\x0b\x10\x0cJ\x08\x08\x13\x10\x80\x80\x80\x80\x02\"\x88\x01\n\x0f\x41\x64sbTransponder\x12\x32\n\x15icao_aircraft_address\x18\x01 \x01(\rR\x13icaoAircraftAddress\x12\x37\n\x17\x61ircraft_identification\x18\x02 \x01(\tR\x16\x61ircraftIdentificationJ\x08\x08\x03\x10\x80\x80\x80\x80\x02\x42\x44\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.common.platform_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common'
  _globals['_PLATFORMDEFINITION']._serialized_start=157
  _globals['_PLATFORMDEFINITION']._serialized_end=850
  _globals['_PLATFORMDEFINITION_MOTIONSOURCE']._serialized_start=730
  _globals['_PLATFORMDEFINITION_MOTIONSOURCE']._serialized_end=804
  _globals['_ADSBTRANSPONDER']._serialized_start=853
  _globals['_ADSBTRANSPONDER']._serialized_end=989
# @@protoc_insertion_point(module_scope)
