# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/common/time.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pi/common/time.proto\x12\x1c\x61\x61lyria.spacetime.api.common\"r\n\x08\x44\x61teTime\x12$\n\x0eunix_time_usec\x18\x01 \x01(\x03R\x0cunixTimeUsec\x12@\n\x08gps_time\x18\x02 \x01(\x0b\x32%.aalyria.spacetime.api.common.GpsTimeR\x07gpsTime\"d\n\x07GpsTime\x12\x1f\n\x0bweek_number\x18\x01 \x01(\x05R\nweekNumber\x12$\n\x0esecond_of_week\x18\x02 \x01(\x05R\x0csecondOfWeek\x12\x12\n\x04usec\x18\x03 \x01(\x05R\x04usec\".\n\x08\x44uration\x12\"\n\x0cmicroseconds\x18\x01 \x02(\x03R\x0cmicroseconds\"\x98\x01\n\x0cTimeInterval\x12\x45\n\nstart_time\x18\x01 \x01(\x0b\x32&.aalyria.spacetime.api.common.DateTimeR\tstartTime\x12\x41\n\x08\x65nd_time\x18\x02 \x01(\x0b\x32&.aalyria.spacetime.api.common.DateTimeR\x07\x65ndTimeBD\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.common.time_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common'
  _globals['_DATETIME']._serialized_start=55
  _globals['_DATETIME']._serialized_end=169
  _globals['_GPSTIME']._serialized_start=171
  _globals['_GPSTIME']._serialized_end=271
  _globals['_DURATION']._serialized_start=273
  _globals['_DURATION']._serialized_end=319
  _globals['_TIMEINTERVAL']._serialized_start=322
  _globals['_TIMEINTERVAL']._serialized_end=474
# @@protoc_insertion_point(module_scope)
