# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/common/wireless_modcod.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n api/common/wireless_modcod.proto\x12\x1c\x61\x61lyria.spacetime.api.common\"\xbf\x05\n\x15\x41\x64\x61ptiveDataRateTable\x12\x0e\n\x02id\x18\x03 \x01(\tR\x02id\x12\xb8\x01\n(carrier_to_noise_plus_interference_steps\x18\x02 \x03(\x0b\x32\x61.aalyria.spacetime.api.common.AdaptiveDataRateTable.CarrierToNoisePlusInterferenceDataRateMappingR#carrierToNoisePlusInterferenceSteps\x12\x95\x01\n\x1breceived_signal_power_steps\x18\x01 \x03(\x0b\x32V.aalyria.spacetime.api.common.AdaptiveDataRateTable.ReceivedSignalPowerDataRateMappingR\x18receivedSignalPowerSteps\x1a\xb0\x01\n-CarrierToNoisePlusInterferenceDataRateMapping\x12V\n)min_carrier_to_noise_plus_interference_db\x18\x01 \x01(\x01R#minCarrierToNoisePlusInterferenceDb\x12\'\n\x10tx_data_rate_bps\x18\x02 \x01(\x01R\rtxDataRateBps\x1a\x8f\x01\n\"ReceivedSignalPowerDataRateMapping\x12@\n\x1dmin_received_signal_power_dbw\x18\x01 \x01(\x01R\x19minReceivedSignalPowerDbw\x12\'\n\x10tx_data_rate_bps\x18\x02 \x01(\x01R\rtxDataRateBpsBD\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.common.wireless_modcod_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common'
  _globals['_ADAPTIVEDATARATETABLE']._serialized_start=67
  _globals['_ADAPTIVEDATARATETABLE']._serialized_end=770
  _globals['_ADAPTIVEDATARATETABLE_CARRIERTONOISEPLUSINTERFERENCEDATARATEMAPPING']._serialized_start=448
  _globals['_ADAPTIVEDATARATETABLE_CARRIERTONOISEPLUSINTERFERENCEDATARATEMAPPING']._serialized_end=624
  _globals['_ADAPTIVEDATARATETABLE_RECEIVEDSIGNALPOWERDATARATEMAPPING']._serialized_start=627
  _globals['_ADAPTIVEDATARATETABLE_RECEIVEDSIGNALPOWERDATARATEMAPPING']._serialized_end=770
# @@protoc_insertion_point(module_scope)
