# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/common/wireless_transceiver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import platform_antenna_pb2 as api_dot_common_dot_platform__antenna__pb2
from api.common import wireless_receiver_pb2 as api_dot_common_dot_wireless__receiver__pb2
from api.common import wireless_transmitter_pb2 as api_dot_common_dot_wireless__transmitter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%api/common/wireless_transceiver.proto\x12\x1c\x61\x61lyria.spacetime.api.common\x1a!api/common/platform_antenna.proto\x1a\"api/common/wireless_receiver.proto\x1a%api/common/wireless_transmitter.proto\"\x8b\x05\n\x10TransceiverModel\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12U\n\x0btransmitter\x18\x02 \x01(\x0b\x32\x33.aalyria.spacetime.api.common.TransmitterDefinitionR\x0btransmitter\x12L\n\x08receiver\x18\x03 \x01(\x0b\x32\x30.aalyria.spacetime.api.common.ReceiverDefinitionR\x08receiver\x12g\n\x15tx_rx_channel_spacing\x18\x04 \x01(\x0b\x32\x34.aalyria.spacetime.api.common.CenterFrequencySpacingR\x12txRxChannelSpacing\x12I\n\x07\x61ntenna\x18\x05 \x01(\x0b\x32/.aalyria.spacetime.api.common.AntennaDefinitionR\x07\x61ntenna\x12=\n\x04macs\x18\x06 \x03(\x0b\x32).aalyria.spacetime.api.common.WirelessMacR\x04macs\x12r\n\x17operational_impairments\x18\x07 \x03(\x0b\x32\x39.aalyria.spacetime.api.common.TransceiverModel.ImpairmentR\x16operationalImpairments\x1a[\n\nImpairment\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12%\n\x0etimestamp_usec\x18\x03 \x01(\x03R\rtimestampUsec\x12\x16\n\x06reason\x18\x04 \x01(\tR\x06reason\"g\n\x12TransceiverModelId\x12\x1f\n\x0bplatform_id\x18\x01 \x01(\tR\nplatformId\x12\x30\n\x14transceiver_model_id\x18\x02 \x01(\tR\x12transceiverModelId\"\xa4\x01\n\x16\x43\x65nterFrequencySpacing\x12\x44\n\x1fmin_center_frequency_spacing_hz\x18\x01 \x01(\x04R\x1bminCenterFrequencySpacingHz\x12\x44\n\x1fmax_center_frequency_spacing_hz\x18\x02 \x01(\x04R\x1bmaxCenterFrequencySpacingHz\"h\n\x0bWirelessMac\x12\x12\n\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n\x04role\x18\x02 \x01(\tR\x04role\x12\'\n\x0fmax_connections\x18\x03 \x01(\x05R\x0emaxConnections*\x08\x08\x64\x10\x80\x80\x80\x80\x02\x42\x44\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.common.wireless_transceiver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common'
  _globals['_TRANSCEIVERMODEL']._serialized_start=182
  _globals['_TRANSCEIVERMODEL']._serialized_end=833
  _globals['_TRANSCEIVERMODEL_IMPAIRMENT']._serialized_start=742
  _globals['_TRANSCEIVERMODEL_IMPAIRMENT']._serialized_end=833
  _globals['_TRANSCEIVERMODELID']._serialized_start=835
  _globals['_TRANSCEIVERMODELID']._serialized_end=938
  _globals['_CENTERFREQUENCYSPACING']._serialized_start=941
  _globals['_CENTERFREQUENCYSPACING']._serialized_end=1105
  _globals['_WIRELESSMAC']._serialized_start=1107
  _globals['_WIRELESSMAC']._serialized_end=1211
# @@protoc_insertion_point(module_scope)
