# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/common/wireless.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import platform_antenna_pb2 as api_dot_common_dot_platform__antenna__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pi/common/wireless.proto\x12\x1c\x61\x61lyria.spacetime.api.common\x1a!api/common/platform_antenna.proto\"\x92\x05\n\x13\x41mplifierDefinition\x12x\n\rconstant_gain\x18\x01 \x01(\x0b\x32Q.aalyria.spacetime.api.common.AmplifierDefinition.ConstantGainAmplifierDefinitionH\x00R\x0c\x63onstantGain\x12l\n\tlow_noise\x18\x02 \x01(\x0b\x32M.aalyria.spacetime.api.common.AmplifierDefinition.LowNoiseAmplifierDefinitionH\x00R\x08lowNoise\x1a\x95\x01\n\x1f\x43onstantGainAmplifierDefinition\x12\x17\n\x07gain_db\x18\x01 \x01(\x01R\x06gainDb\x12!\n\x0cnoise_factor\x18\x02 \x01(\x01R\x0bnoiseFactor\x12\x36\n\x17reference_temperature_k\x18\x03 \x01(\x01R\x15referenceTemperatureK\x1a\xe8\x01\n\x1bLowNoiseAmplifierDefinition\x12%\n\x0fpre_lna_gain_db\x18\x01 \x01(\x01R\x0cpreLnaGainDb\x12\x1e\n\x0blna_gain_db\x18\x02 \x01(\x01R\tlnaGainDb\x12\'\n\x10post_lna_gain_db\x18\x03 \x01(\x01R\rpostLnaGainDb\x12!\n\x0cnoise_factor\x18\x04 \x01(\x01R\x0bnoiseFactor\x12\x36\n\x17reference_temperature_k\x18\x05 \x01(\x01R\x15referenceTemperatureKB\x10\n\x0e\x61mplifier_type\"K\n\x0eMiscGainOrLoss\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12%\n\x0fgain_or_loss_db\x18\x02 \x01(\x01R\x0cgainOrLossDb\"\xab\x01\n\x06Signal\x12.\n\x13\x63\x65nter_frequency_hz\x18\x01 \x01(\x04R\x11\x63\x65nterFrequencyHz\x12!\n\x0c\x62\x61ndwidth_hz\x18\x02 \x01(\x04R\x0b\x62\x61ndwidthHz\x12N\n\x0cpolarization\x18\x03 \x01(\x0b\x32*.aalyria.spacetime.api.common.PolarizationR\x0cpolarizationBD\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.common.wireless_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common'
  _globals['_AMPLIFIERDEFINITION']._serialized_start=95
  _globals['_AMPLIFIERDEFINITION']._serialized_end=753
  _globals['_AMPLIFIERDEFINITION_CONSTANTGAINAMPLIFIERDEFINITION']._serialized_start=351
  _globals['_AMPLIFIERDEFINITION_CONSTANTGAINAMPLIFIERDEFINITION']._serialized_end=500
  _globals['_AMPLIFIERDEFINITION_LOWNOISEAMPLIFIERDEFINITION']._serialized_start=503
  _globals['_AMPLIFIERDEFINITION_LOWNOISEAMPLIFIERDEFINITION']._serialized_end=735
  _globals['_MISCGAINORLOSS']._serialized_start=755
  _globals['_MISCGAINORLOSS']._serialized_end=830
  _globals['_SIGNAL']._serialized_start=833
  _globals['_SIGNAL']._serialized_end=1004
# @@protoc_insertion_point(module_scope)
