# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/common/wireless_transmitter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import channel_pb2 as api_dot_common_dot_channel__pb2
from api.common import wireless_pb2 as api_dot_common_dot_wireless__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%api/common/wireless_transmitter.proto\x12\x1c\x61\x61lyria.spacetime.api.common\x1a\x18\x61pi/common/channel.proto\x1a\x19\x61pi/common/wireless.proto\"\x8e\x02\n\nTxChannels\x12O\n\x07\x63hannel\x18\x01 \x03(\x0b\x32\x35.aalyria.spacetime.api.common.TxChannels.ChannelEntryR\x07\x63hannel\x1a\x39\n\x0fTxChannelParams\x12&\n\x0fmax_power_watts\x18\x01 \x01(\x01R\rmaxPowerWatts\x1at\n\x0c\x43hannelEntry\x12\x10\n\x03key\x18\x01 \x01(\x04R\x03key\x12N\n\x05value\x18\x02 \x01(\x0b\x32\x38.aalyria.spacetime.api.common.TxChannels.TxChannelParamsR\x05value:\x02\x38\x01\"\xa3\x04\n\x15TransmitterDefinition\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x64\n\x0b\x63hannel_set\x18\x0e \x03(\x0b\x32\x43.aalyria.spacetime.api.common.TransmitterDefinition.ChannelSetEntryR\nchannelSet\x12n\n\x18\x63hannel_selection_method\x18\r \x01(\x0e\x32\x34.aalyria.spacetime.api.common.ChannelSelectionMethodR\x16\x63hannelSelectionMethod\x12k\n\x16signal_processing_step\x18\x0f \x03(\x0b\x32\x35.aalyria.spacetime.api.common.TransmitSignalProcessorR\x14signalProcessingStep\x12.\n\x13\x63overage_heatmap_id\x18\x11 \x01(\tR\x11\x63overageHeatmapId\x1ag\n\x0f\x43hannelSetEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12>\n\x05value\x18\x02 \x01(\x0b\x32(.aalyria.spacetime.api.common.TxChannelsR\x05value:\x02\x38\x01J\x04\x08\x01\x10\x02J\x04\x08\x03\x10\rJ\x04\x08\x10\x10\x11J\x08\x08\x12\x10\x80\x80\x80\x80\x02\"\xc6\x01\n\x17TransmitSignalProcessor\x12Q\n\tamplifier\x18\x01 \x01(\x0b\x32\x31.aalyria.spacetime.api.common.AmplifierDefinitionH\x00R\tamplifier\x12P\n\x0cgain_or_loss\x18\x02 \x01(\x0b\x32,.aalyria.spacetime.api.common.MiscGainOrLossH\x00R\ngainOrLossB\x06\n\x04typeBD\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.common.wireless_transmitter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common'
  _TXCHANNELS_CHANNELENTRY._options = None
  _TXCHANNELS_CHANNELENTRY._serialized_options = b'8\001'
  _TRANSMITTERDEFINITION_CHANNELSETENTRY._options = None
  _TRANSMITTERDEFINITION_CHANNELSETENTRY._serialized_options = b'8\001'
  _globals['_TXCHANNELS']._serialized_start=125
  _globals['_TXCHANNELS']._serialized_end=395
  _globals['_TXCHANNELS_TXCHANNELPARAMS']._serialized_start=220
  _globals['_TXCHANNELS_TXCHANNELPARAMS']._serialized_end=277
  _globals['_TXCHANNELS_CHANNELENTRY']._serialized_start=279
  _globals['_TXCHANNELS_CHANNELENTRY']._serialized_end=395
  _globals['_TRANSMITTERDEFINITION']._serialized_start=398
  _globals['_TRANSMITTERDEFINITION']._serialized_end=945
  _globals['_TRANSMITTERDEFINITION_CHANNELSETENTRY']._serialized_start=814
  _globals['_TRANSMITTERDEFINITION_CHANNELSETENTRY']._serialized_end=917
  _globals['_TRANSMITSIGNALPROCESSOR']._serialized_start=948
  _globals['_TRANSMITSIGNALPROCESSOR']._serialized_end=1146
# @@protoc_insertion_point(module_scope)
