# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/types/ethernet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pi/types/ethernet.proto\x12\x1b\x61\x61lyria.spacetime.api.types\"\xab\x02\n\tEtherType\x12K\n\nwell_known\x18\x01 \x01(\x0e\x32*.aalyria.spacetime.api.types.EtherType.EthH\x00R\twellKnown\x12\x1c\n\x08\x65xplicit\x18\x02 \x01(\rH\x00R\x08\x65xplicit\"\xa9\x01\n\x03\x45th\x12\x13\n\x0f\x45TH_UNSPECIFIED\x10\x00\x12\r\n\x08\x45TH_IPV4\x10\x80\x10\x12\x0c\n\x07\x45TH_ARP\x10\x86\x10\x12\x13\n\rETH_VLAN_CTAG\x10\x80\x82\x02\x12\x0e\n\x08\x45TH_IPV6\x10\xdd\x8d\x02\x12\x0e\n\x08\x45TH_MPLS\x10\xc7\x90\x02\x12\x17\n\x11\x45TH_MPLS_UPSTREAM\x10\xc8\x90\x02\x12\x13\n\rETH_VLAN_STAG\x10\xa8\x91\x02\x12\r\n\x07\x45TH_PBB\x10\xe7\x91\x02\x42\x07\n\x05valueBB\n\x1f\x63om.aalyria.spacetime.api.typesZ\x1f\x61\x61lyria.com/spacetime/api/types')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.types.ethernet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.aalyria.spacetime.api.typesZ\037aalyria.com/spacetime/api/types'
  _globals['_ETHERTYPE']._serialized_start=58
  _globals['_ETHERTYPE']._serialized_end=357
  _globals['_ETHERTYPE_ETH']._serialized_start=179
  _globals['_ETHERTYPE_ETH']._serialized_end=348
# @@protoc_insertion_point(module_scope)
