# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.nbi.v1alpha import nbi_pb2 as api_dot_nbi_dot_v1alpha_dot_nbi__pb2


class NetOpsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEntity = channel.unary_unary(
                '/aalyria.spacetime.api.nbi.v1alpha.NetOps/GetEntity',
                request_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.GetEntityRequest.SerializeToString,
                response_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.Entity.FromString,
                )
        self.CreateEntity = channel.unary_unary(
                '/aalyria.spacetime.api.nbi.v1alpha.NetOps/CreateEntity',
                request_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.CreateEntityRequest.SerializeToString,
                response_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.Entity.FromString,
                )
        self.UpdateEntity = channel.unary_unary(
                '/aalyria.spacetime.api.nbi.v1alpha.NetOps/UpdateEntity',
                request_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.UpdateEntityRequest.SerializeToString,
                response_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.Entity.FromString,
                )
        self.ListEntities = channel.unary_unary(
                '/aalyria.spacetime.api.nbi.v1alpha.NetOps/ListEntities',
                request_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesRequest.SerializeToString,
                response_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesResponse.FromString,
                )
        self.ListEntitiesOverTime = channel.unary_unary(
                '/aalyria.spacetime.api.nbi.v1alpha.NetOps/ListEntitiesOverTime',
                request_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesOverTimeRequest.SerializeToString,
                response_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesOverTimeResponse.FromString,
                )
        self.DeleteEntity = channel.unary_unary(
                '/aalyria.spacetime.api.nbi.v1alpha.NetOps/DeleteEntity',
                request_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.DeleteEntityRequest.SerializeToString,
                response_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.DeleteEntityResponse.FromString,
                )
        self.LoadScenario = channel.unary_unary(
                '/aalyria.spacetime.api.nbi.v1alpha.NetOps/LoadScenario',
                request_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.LoadScenarioRequest.SerializeToString,
                response_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.LoadScenarioResponse.FromString,
                )


class NetOpsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntitiesOverTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetOpsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntity,
                    request_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.GetEntityRequest.FromString,
                    response_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.Entity.SerializeToString,
            ),
            'CreateEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEntity,
                    request_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.CreateEntityRequest.FromString,
                    response_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.Entity.SerializeToString,
            ),
            'UpdateEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEntity,
                    request_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.UpdateEntityRequest.FromString,
                    response_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.Entity.SerializeToString,
            ),
            'ListEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntities,
                    request_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesRequest.FromString,
                    response_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesResponse.SerializeToString,
            ),
            'ListEntitiesOverTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntitiesOverTime,
                    request_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesOverTimeRequest.FromString,
                    response_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesOverTimeResponse.SerializeToString,
            ),
            'DeleteEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEntity,
                    request_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.DeleteEntityRequest.FromString,
                    response_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.DeleteEntityResponse.SerializeToString,
            ),
            'LoadScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadScenario,
                    request_deserializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.LoadScenarioRequest.FromString,
                    response_serializer=api_dot_nbi_dot_v1alpha_dot_nbi__pb2.LoadScenarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aalyria.spacetime.api.nbi.v1alpha.NetOps', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NetOps(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aalyria.spacetime.api.nbi.v1alpha.NetOps/GetEntity',
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.GetEntityRequest.SerializeToString,
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.Entity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aalyria.spacetime.api.nbi.v1alpha.NetOps/CreateEntity',
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.CreateEntityRequest.SerializeToString,
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.Entity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aalyria.spacetime.api.nbi.v1alpha.NetOps/UpdateEntity',
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.UpdateEntityRequest.SerializeToString,
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.Entity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aalyria.spacetime.api.nbi.v1alpha.NetOps/ListEntities',
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesRequest.SerializeToString,
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListEntitiesOverTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aalyria.spacetime.api.nbi.v1alpha.NetOps/ListEntitiesOverTime',
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesOverTimeRequest.SerializeToString,
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.ListEntitiesOverTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aalyria.spacetime.api.nbi.v1alpha.NetOps/DeleteEntity',
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.DeleteEntityRequest.SerializeToString,
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.DeleteEntityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aalyria.spacetime.api.nbi.v1alpha.NetOps/LoadScenario',
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.LoadScenarioRequest.SerializeToString,
            api_dot_nbi_dot_v1alpha_dot_nbi__pb2.LoadScenarioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
