# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.nbi.v1alpha import signal_propagation_pb2 as api_dot_nbi_dot_v1alpha_dot_signal__propagation__pb2


class SignalPropagationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/aalyria.spacetime.api.nbi.v1alpha.SignalPropagation/Evaluate',
                request_serializer=api_dot_nbi_dot_v1alpha_dot_signal__propagation__pb2.SignalPropagationRequest.SerializeToString,
                response_deserializer=api_dot_nbi_dot_v1alpha_dot_signal__propagation__pb2.SignalPropagationResponse.FromString,
                )


class SignalPropagationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalPropagationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=api_dot_nbi_dot_v1alpha_dot_signal__propagation__pb2.SignalPropagationRequest.FromString,
                    response_serializer=api_dot_nbi_dot_v1alpha_dot_signal__propagation__pb2.SignalPropagationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aalyria.spacetime.api.nbi.v1alpha.SignalPropagation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SignalPropagation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aalyria.spacetime.api.nbi.v1alpha.SignalPropagation/Evaluate',
            api_dot_nbi_dot_v1alpha_dot_signal__propagation__pb2.SignalPropagationRequest.SerializeToString,
            api_dot_nbi_dot_v1alpha_dot_signal__propagation__pb2.SignalPropagationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
