# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/nbi/v1alpha/signal_propagation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import wireless_transceiver_pb2 as api_dot_common_dot_wireless__transceiver__pb2
from api.nbi.v1alpha.resources import coverage_pb2 as api_dot_nbi_dot_v1alpha_dot_resources_dot_coverage__pb2
from api.nbi.v1alpha.resources import wireless_evaluation_pb2 as api_dot_nbi_dot_v1alpha_dot_resources_dot_wireless__evaluation__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.type import interval_pb2 as google_dot_type_dot_interval__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(api/nbi/v1alpha/signal_propagation.proto\x12!aalyria.spacetime.api.nbi.v1alpha\x1a%api/common/wireless_transceiver.proto\x1a(api/nbi/v1alpha/resources/coverage.proto\x1a\x33\x61pi/nbi/v1alpha/resources/wireless_evaluation.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1agoogle/type/interval.proto\"\xa0\x06\n\x18SignalPropagationRequest\x12m\n\x11transmitter_model\x18\x01 \x01(\x0b\x32@.aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverProviderR\x10transmitterModel\x12&\n\x0f\x62\x61nd_profile_id\x18\x02 \x01(\tR\rbandProfileId\x12X\n\x06target\x18\x03 \x01(\x0b\x32@.aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverProviderR\x06target\x12X\n\x08\x63overage\x18\x04 \x01(\x0b\x32<.aalyria.spacetime.api.nbi.v1alpha.resources.CoordinateArrayR\x08\x63overage\x12\x44\n\x11\x61nalysis_interval\x18\x06 \x01(\x0b\x32\x15.google.type.IntervalH\x00R\x10\x61nalysisInterval\x12G\n\x10\x61nalysis_instant\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00R\x0f\x61nalysisInstant\x12\x36\n\tstep_size\x18\x07 \x01(\x0b\x32\x19.google.protobuf.DurationR\x08stepSize\x12\\\n\x1dspatial_propagation_step_size\x18\t \x01(\x0b\x32\x19.google.protobuf.DurationR\x1aspatialPropagationStepSize\x12\x37\n\x17\x65xplain_inaccessibility\x18\x08 \x01(\x08R\x16\x65xplainInaccessibility\x12J\n\x13reference_data_time\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x11referenceDataTimeB\x0f\n\ranalysis_time\"\x81\x01\n\x19SignalPropagationResponse\x12\x64\n\x0f\x61\x63\x63\x65ss_interval\x18\x01 \x03(\x0b\x32;.aalyria.spacetime.api.nbi.v1alpha.resources.AccessIntervalR\x0e\x61\x63\x63\x65ssInterval2\x9d\x01\n\x11SignalPropagation\x12\x87\x01\n\x08\x45valuate\x12;.aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest\x1a<.aalyria.spacetime.api.nbi.v1alpha.SignalPropagationResponse\"\x00\x42N\n%com.aalyria.spacetime.api.nbi.v1alphaZ%aalyria.com/spacetime/api/nbi/v1alpha')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.nbi.v1alpha.signal_propagation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.aalyria.spacetime.api.nbi.v1alphaZ%aalyria.com/spacetime/api/nbi/v1alpha'
  _globals['_SIGNALPROPAGATIONREQUEST']._serialized_start=307
  _globals['_SIGNALPROPAGATIONREQUEST']._serialized_end=1107
  _globals['_SIGNALPROPAGATIONRESPONSE']._serialized_start=1110
  _globals['_SIGNALPROPAGATIONRESPONSE']._serialized_end=1239
  _globals['_SIGNALPROPAGATION']._serialized_start=1242
  _globals['_SIGNALPROPAGATION']._serialized_end=1399
# @@protoc_insertion_point(module_scope)
