# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/nbi/v1alpha/resources/devices_in_region.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api.common import wireless_transceiver_pb2 as api_dot_common_dot_wireless__transceiver__pb2
from api.nbi.v1alpha.resources import coverage_pb2 as api_dot_nbi_dot_v1alpha_dot_resources_dot_coverage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1api/nbi/v1alpha/resources/devices_in_region.proto\x12+aalyria.spacetime.api.nbi.v1alpha.resources\x1a%api/common/wireless_transceiver.proto\x1a(api/nbi/v1alpha/resources/coverage.proto\"\xa7\x02\n\x0f\x44\x65vicesInRegion\x12-\n\x13\x64\x65vice_in_region_id\x18\x01 \x01(\tR\x10\x64\x65viceInRegionId\x12Y\n\x10reference_device\x18\x02 \x01(\x0b\x32..aalyria.spacetime.api.common.TransceiverModelR\x0freferenceDevice\x12\x62\n\x0fregion_on_earth\x18\x03 \x01(\x0b\x32:.aalyria.spacetime.api.nbi.v1alpha.resources.GeoJsonRegionR\rregionOnEarth\x12&\n\x0f\x64\x65vices_per_km2\x18\x04 \x01(\x01R\rdevicesPerKm2Bb\n/com.aalyria.spacetime.api.nbi.v1alpha.resourcesZ/aalyria.com/spacetime/api/nbi/v1alpha/resources')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.nbi.v1alpha.resources.devices_in_region_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n/com.aalyria.spacetime.api.nbi.v1alpha.resourcesZ/aalyria.com/spacetime/api/nbi/v1alpha/resources'
  _globals['_DEVICESINREGION']._serialized_start=180
  _globals['_DEVICESINREGION']._serialized_end=475
# @@protoc_insertion_point(module_scope)
